name: PServerPlus
version: '${project.version}'
main: fr.plhume.pserverplus.PServerPlus
api-version: '1.19'

commands:
  fly:
    description: Permet d'activer ou de désactiver son propre vol ou celui d'un autre joueur.
    aliases:
      - vol
